version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: albums-postgres
    env_file:
      .env
    logging:
      options:
        max-size: 10m
        max-file: "3"
    networks:
      - base-network
    restart: always
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data
      - ./sql/postgres/0001_create_databases.sql:/docker-entrypoint-initdb.d/0001_create_databases.sql
      - ./sql/postgres/0005_create_tables.sql:/docker-entrypoint-initdb.d/0005_create_tables.sql
      - ./sql/postgres/0010_insert_albums.sql:/docker-entrypoint-initdb.d/0010_insert_albums.sql
  mysql:
    image: mysql:latest
    container_name: albums-mysql
    env_file:
      .env
    logging:
      options:
        max-size: 10m
        max-file: "3"
    networks:
      - base-network
    restart: always
    volumes:
      - ./data/mysql_data:/var/lib/mysql
      - ./sql/mysql/0001_create_tables.sql:/docker-entrypoint-initdb.d/0001_create_tables.sql
      - ./sql/mysql/0010_insert_albums.sql:/docker-entrypoint-initdb.d/0010_insert_albums.sql
      - ./conf/my.cnf:/etc/mysql/my.cnf
  web:
    build: .
    depends_on:
      postgres:
        condition: service_started
      mysql:
        condition: service_started
    deploy:
      replicas: 1
    env_file:
      .env
    logging:
      options:
        max-size: 10m
        max-file: "3"
    networks:
      - base-network
    restart: always
  nginx:
    image: nginx:latest
    depends_on:
      - web
    networks:
      - base-network
    ports:
      - "4000:4000"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro

networks:
  base-network:
