version: '3.8'

services:
  db:
    image: postgres
    container_name: albums-db
    env_file:
      .env
    logging:
      options:
        max-size: 10m
        max-file: "3"
    networks:
      - base-network
    restart: always
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data
      - ./sql/0001_create_databases.sql:/docker-entrypoint-initdb.d/0001_create_databases.sql
      - ./sql/0005_create_tables.sql:/docker-entrypoint-initdb.d/0005_create_tables.sql
      - ./sql/0010_insert_albums.sql:/docker-entrypoint-initdb.d/0010_insert_albums.sql
  web:
    build: .
    depends_on:
      db:
        condition: service_started
    deploy:
      replicas: 5
    env_file:
      .env
    logging:
      options:
        max-size: 10m
        max-file: "3"
    networks:
      - base-network
    restart: always
  nginx:
    image: nginx:latest
    depends_on:
      - web
    networks:
      - base-network
    ports:
      - "4000:4000"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro

networks:
  base-network:
