version: '3.8'

services:
  web:
    image: web-service-gin
    container_name: albums-web
    env_file:
      .env
    ports:
      - "8080:8080"
    restart: always
    networks:
      - base-network

  db:
    image: postgres:10.5
    container_name: albums-db
    restart: always
    env_file:
      .env
    logging:
      options:
        max-size: 10m
        max-file: "3"
    networks:
      - base-network
    volumes:
      - ./rest/data/postgres_data:/var/lib/postgresql/data
      - ./rest/data/sql/0001_create_databases.sql:/docker-entrypoint-initdb.d/0001_create_databases.sql
      - ./rest/data/sql/0005_create_tables.sql:/docker-entrypoint-initdb.d/0005_create_tables.sql
      - ./rest/data/sql/0010_insert_albums.sql:/docker-entrypoint-initdb.d/0010_insert_albums.sql

networks:
  base-network:
