version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    env_file:
      .env
    ports:
      - "33060:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./rest/data/sql/0001_create_tables.sql:/docker-entrypoint-initdb.d/0001_create_tables.sql
      - ./rest/data/sql/0010_insert_albums.sql:/docker-entrypoint-initdb.d/0010_insert_albums.sql
      # - ./db/my.cnf:/etc/mysql/my.cnf

volumes:
  mysql_data:
